### ISSUE TITLE
Scotch missing file

### ISSUE THREAD

**Issue by covarj** [crewesleo/SeisElastic2D#1]
Hi Wenyong,
When I tried to run "./configure FC=ifort --with-mpi" I got the following error:

config.status: error: cannot find input file: `./src/meshfem2D/scotch/src/Makefile.inc.in'

I noticed there was a tar file with the source files to build Scotch, but the Makefile.inc.in file is not there.
Any idea how to fix this? 
Thanks

**Comment by crewesleo** [comment]
Hi Raul, 

I think in the cluster, you don't install the scotch library.  You may need to install SCOTCH first. 

You can find one package scotch_6.0.4.tar.gz under the folder of "specfem2d/src/meshfem2D/". 

You will find one INSTALL.txt file after unziping it.  

Install SCOTCH first following the instructions step by step in INSTALL.txt.

Then configure SPECFEM2D indicating the location of SCOTCH:

./configure FC=ifort --with-mpi --with-scotch-dir=/home/SeisElastic2D/specfem2d/src/meshfem2D/scotch_6.0.4

Do you mean Makefile.inc file when installing SCOTCH?

Makefile.inc file contains the configurations selected from the the folder of scotch_6.0.4/src/Make.inc.

You may need to obtain the Makefile.inc file using the following command:

cp Make.inc/Makefile.inc.xxxx_xxx_xxx Makefile.inc

According to the setting of your cluster, you need to select which one to copy.

This should help.

regards,

wenyong

**Comment by covarj** [comment]
Thanks Wenyong!

One more question. Do you think it would be a good idea to replace the specfem2D folder in the Seiselastic2D repository by the latest specfem2D folder in the original repository?

I noticed that the specfem2D version in SeisElastic2D dates back to 2014 and there is a more recent version in the original specfem2D github. Did you make significant changes to the specfem2D source files? 

I know the "DATA/Par_file" file is slightly different on each version. However, I think it could be relatively easy to modify the scripts that set the parameters in Par_file. If you think this is a good idea I could collaborate with you in including the latest version of specfem2D in your package.

Cheers,

Raul

**Comment by crewesleo** [comment]
Hi Raul,

I think I used old version of specfem2D. I have changed the codes in specfem2D a lot for calculating the sensitivity kernels in anisotropic and viscoelastic media. If you use the latest version of specfem2D online, SeisElastic2D will not be set up successfully.

Wenyong
